### ISSUE TITLE
Linker error with "flexRelease_x64.lib'

### ISSUE THREAD

**Issue by alexhillel** [vinz9/FlexCHOP#1]
I'm trying to compile using VS2015, and I've followed the compilation instructions. I've included the directories '/flex' and '/flex/include' of the downloaded Flex 1.1 library, but I'm now getting a linker error LNK1181	cannot open input file 'flexRelease_x64.lib' during the build process. I don't see this file anywhere - what steps do I need to take?

**Comment by vinz9** [comment]
Hello,
Make sure you compile for x64, not win32, then the path and lib files names should be correct.
I never updated the Visual Studio project for win32.
