### ISSUE TITLE
"Failed to load the .dll" when using flex

### ISSUE THREAD

**Issue by ulyssesdotcodes** [vinz9/FlexCHOP#3]
The project compiles and links correctly, but whenever the code uses the flex library (for example `NvFlexDeviceGetSuggestedOrdinal`) TouchDesigner spits out the error "Failed to load .dll". When the flex library usage is commented out, the dll loads.

Minimum repo: edit the TouchDesigner CudaTOP sample to add flex to the project and these two lines to `CudaTOP`'s initialization

```
	int g_device = -1;
	g_device = NvFlexDeviceGetSuggestedOrdinal();
```

This is with everything compiled for x64.

**Comment by vinz9** [comment]
Sorry missed that, I think you need to add NvFlexDeviceRelease_x64.dll along the other dlls. Otherwise indeed you can comment out the lines that use NvFlexDevice* though creating the special cuda context makes the sim a little bit faster.
